### ISSUE TITLE
stepper form with server action

### ISSUE THREAD

**Issue by dzakyabdurhmn** [damianricobelli/stepperize#13]
hello @damianricobelli as you said in the documentation that you can use stepper with server action. but can you write the sample code for me?

**Comment by damianricobelli** [comment]
Please open a new issue if you find that the new documents do not solve your problem

**Comment by cmoleka** [comment]
My way of doing it is adding the server actions within the onSubmit function.

You can select which step executes what by doing the following:

```
function onSubmit(values) {

if (stepper.get("stepId").id === stepper.current.id) {

action()
...
}
}
```

Let me know if anyone has a better way.
