### ISSUE TITLE
Shared context between steps

### ISSUE THREAD

**Issue by blissfulldev** [damianricobelli/stepperize#14]
Hi @damianricobelli this is really nice component you have created.
I was wondering if it will be a good idea to share state between different steps using stepper context out of the box. I believe that in many of the use case next step will be dependent on the action performed by previous steps hence sharing of previous step data.

**Comment by damianricobelli** [comment]
I am closing this issue as you will be able to solve this through the new `@stepperize/react` library, which allows you to send metadata and persist whatever you need!
