### ISSUE TITLE
expose isError, isDisabled similar to PR into shadcn

### ISSUE THREAD

**Issue by nmashchenko** [damianricobelli/stepperize#34]
hey dude, awesome work, I actually was looking for abstracted solution like that but I think really important thing u are currently missing is a possibility to "lock" steps (e.g. user has to do some actions before going to next step). This somehow relates to error that should also prevent user to go further

Anyways, excited to see future updates!

**Comment by damianricobelli** [comment]
Hey, thanks for your comment. I'm glad you like the library.

Regarding your question, this is something that will be on the developer's side as it is beyond the scope of the Stepper primitive. You can use whatever logic you see fit to create these `error` or `loading` states.
