### ISSUE TITLE
Found broken `/docs/getting-started/scoped` link. Please fix!

### ISSUE THREAD

**Issue by vfritzon** [damianricobelli/stepperize#39]
From https://stepperize.vercel.app/docs/getting-started/define-stepper

**Comment by damianricobelli** [comment]
It works for me. Could you tell me what you're seeing?

**Comment by none23** [comment]
This link is broken 
![image](https://github.com/user-attachments/assets/ba55c0fe-eeec-41e9-b952-2279c24b3d43)
![image](https://github.com/user-attachments/assets/e8723832-9f61-48ca-b7ef-f63f22bb01a2)

I've opened a PR
