### ISSUE TITLE
Error when build time on v3

### ISSUE THREAD

**Issue by blobgetblob** [damianricobelli/stepperize#54]
i have type error when building on my nextjs project, how to solve this?

```
const { Scoped, useStepper } = defineStepper(
{ id: 'step-category', title: 'Category', description: 'Select a category of your project', icon: Folder },
{ id: 'step-template', title: 'Template', description: 'Select template for your project', icon: FileCheck2 },
{ id: 'step-info', title: 'Info', description: 'Fill your project informations', icon: Info },
{ id: 'step-details', title: 'Details', description: 'Provide extra details of your project', icon: AlignJustify },
{ id: 'step-flows', title: 'Flows', description: 'Arrange and setting your project flows', icon: ArrowUpFromDot },
{ id: 'step-receivers', title: 'Receivers', description: 'Add additional receivers to your project', icon: Users },
{ id: 'step-review', title: 'Review', description: 'Review your project before creation', icon: Eye },
)
```

#19 172.4 demplon-admin-web:build: ./app/(dts)/dts-create/page.tsx:234:3
#19 172.4 demplon-admin-web:build: Type error: Expected 0 arguments, but got 7.
#19 172.4 demplon-admin-web:build: 
#19 172.4 demplon-admin-web:build:   232 | 	// eslint-disable-next-line no-use-before-define
#19 172.4 demplon-admin-web:build:   233 | 	const *** Scoped, useStepper *** = defineStepper(
#19 172.4 demplon-admin-web:build: > 234 | 		*** id: 'step-category', title: 'Category', description: 'Select a category of your project', icon: Folder ***,
#19 172.4 demplon-admin-web:build:       | 		^
#19 172.4 demplon-admin-web:build:   235 | 		*** id: 'step-template', title: 'Template', description: 'Select template for your project', icon: FileCheck2 ***,
#19 172.4 demplon-admin-web:build:   236 | 		*** id: 'step-info', title: 'Info', description: 'Fill your project informations', icon: Info ***,
#19 172.4 demplon-admin-web:build:   237 | 		*** id: 'step-details', title: 'Details', description: 'Provide extra details of your project', icon: AlignJustify ***,
#19 172.6 demplon-admin-web:build: npm ERR! Lifecycle script `build` failed with error: 
#19 172.6 demplon-admin-web:build: npm ERR! Error: command failed 
#19 172.6 demplon-admin-web:build: npm ERR!   in workspace: demplon-admin-web@0.0.2 
#19 172.6 demplon-admin-web:build: npm ERR!   at location: /app/apps/demplon-admin-web 
#19 172.6 demplon-admin-web:build: ERROR: command finished with error: command (/app/apps/demplon-admin-web) /usr/local/bin/npm run build exited (1)
#19 172.6 demplon-admin-web#build: command (/app/apps/demplon-admin-web) /usr/local/bin/npm run build exited (1)

**Comment by damianricobelli** [comment]
@blobgetblob couldn't understand what the error is since it seems that the error corresponds to another line of code where you are possibly using some value of the defineStepper. Could you share with me a reproducible example of the error in Codesandbox or similar tool?

**Comment by farreltobias** [comment]
Hey, I got the same error, here's more description:

<img width="762" alt="image" src="https://github.com/user-attachments/assets/08257ab5-b2ea-4346-8deb-e1def633f358" />
