### ISSUE TITLE
Add `index` property for steps

### ISSUE THREAD

**Issue by wottpal** [damianricobelli/stepperize#66]
It's useful to get an (automatic) `index` value for each step, e.g. when showing something like "Step {index} of {total}".

Currently I'm using a small helper function like:

```ts
function getStepIndex(step: (typeof steps)[number]) {
  return steps.findIndex((_step) => step.id === _step.id) as number
}
```

**Comment by damianricobelli** [comment]
In v3.1 an index is added to the current step. I can definitely add this

**Comment by wottpal** [comment]
Oh sweet, yes that works perfectly fine. Didn't seeb this release yet.
