### ISSUE TITLE
Idea: Carry accumulated form date

### ISSUE THREAD

**Issue by wottpal** [damianricobelli/stepperize#68]
Sorry for opening three issues at once, these are just the points I've noted to myself after building my first stepper form with this library (btw you can check it out [here](https://find-your-cruise.com/blog/cruise-sustainability#our-carbon-calculator), also feel free to add it to a showcase section in the docs if you plan one). This one is just an idea (and there might even be stuff speaking against it), but I still think it's worth discussing as forms are a very very common use cases for steppers.

**Status quo:** If you're building a form it only holds the schema & data of the current step only. But often you're only splitting a form into multiple steps because of UX-reasons and want to submit the data all together. So what you would need to be doing is something like:

```ts
const stepper = useStepper()
const [data, setData] = useState<Partial<TSchema1 & TSchema2 & …>>({})

async function onSubmit(values: z.infer<typeof stepper.current.schema>) {
    setData((prev) => ({ ...prev, ...values }))
    stepper.next()
}
```

**Idea:** The stepper could hold & merge the data and provide it in a typed manner (maybe even giving type guarantees for steps that are already done).

```ts
const { stepper, data } = useStepper()

async function onSubmit(values: z.infer<typeof stepper.current.schema>) {
    stepper.next(values)
    // Or alternatively with a dedicated `setFieldData` function
}
```

**Comment by damianricobelli** [comment]
While I understand your point and why you would need this, I don't think the library should be in charge of storing step values between steps. There can be many ways to do this either with a state management library or through React API's, so I prefer to leave it up to developers to experiment with the best way that suits them.

**Comment by wottpal** [comment]
Very fair point! It might make sense though to at least add my example from above to the docs (form example). Up to you to close this.

**Comment by damianricobelli** [comment]
Yes, I have in my roadmap added an example for sharing data between steps. You can even see it in the examples, although it is still in `Coming soon...` status.

![image](https://github.com/user-attachments/assets/2c070aa6-7794-4aa5-87ed-3399e05a694f)
